// Auto-generated by scripts/compile-catalogs.mjs — DO NOT EDIT
import type { TranslationCatalog, SupportedLocale } from "../types.js";

const en: TranslationCatalog = {
  "cli.welcome": "CIG — Compute Intelligence Graph CLI",
  "cli.connecting": "Connecting to {provider}…",
  "cli.discoveryStarted": "Discovery started for {target}",
  "cli.discoveryComplete": "Discovery complete: {count, plural, one {# resource} other {# resources}} found",
  "cli.authSuccess": "Authenticated successfully as {email}",
  "cli.authFailed": "Authentication failed: {reason}",
  "cli.configSaved": "Configuration saved to {path}",
  "cli.error.missingArg": "Missing required argument: {arg}",
  "cli.error.invalidProvider": "Invalid provider: {provider}. Supported: {supported}",
  "cli.help.usage": "Usage: cig <command> [options]",
  "cli.help.commands": "Available commands:",
  "cli.help.options": "Global options:"
};

const es: TranslationCatalog = {
  "cli.welcome": "CIG — Compute Intelligence Graph CLI",
  "cli.connecting": "Conectando a {provider}…",
  "cli.discoveryStarted": "Descubrimiento iniciado para {target}",
  "cli.discoveryComplete": "Descubrimiento completo: {count, plural, one {# recurso} other {# recursos}} encontrados",
  "cli.authSuccess": "Autenticado exitosamente como {email}",
  "cli.authFailed": "Fallo de autenticación: {reason}",
  "cli.configSaved": "Configuración guardada en {path}",
  "cli.error.missingArg": "Argumento requerido faltante: {arg}",
  "cli.error.invalidProvider": "Proveedor inválido: {provider}. Soportados: {supported}",
  "cli.help.usage": "Uso: cig <comando> [opciones]",
  "cli.help.commands": "Comandos disponibles:",
  "cli.help.options": "Opciones globales:"
};

const zh: TranslationCatalog = {
  "cli.welcome": "CIG — Compute Intelligence Graph 命令行工具",
  "cli.connecting": "正在连接 {provider}…",
  "cli.discoveryStarted": "已开始发现 {target}",
  "cli.discoveryComplete": "发现完成：找到 {count} 个资源",
  "cli.authSuccess": "已成功以 {email} 身份认证",
  "cli.authFailed": "认证失败：{reason}",
  "cli.configSaved": "配置已保存到 {path}",
  "cli.error.missingArg": "缺少必需参数：{arg}",
  "cli.error.invalidProvider": "无效提供商：{provider}。支持的有：{supported}",
  "cli.help.usage": "用法：cig <命令> [选项]",
  "cli.help.commands": "可用命令：",
  "cli.help.options": "全局选项："
};

const catalogs: Record<SupportedLocale, TranslationCatalog> = { en, es, zh };

export default catalogs;
export { en, es, zh };
