// Auto-generated by scripts/compile-catalogs.mjs — DO NOT EDIT
import type { TranslationCatalog, SupportedLocale } from "../types.js";

const en: TranslationCatalog = {
  "dashboard.welcome": "Welcome to CIG Dashboard",
  "dashboard.noResources": "No resources discovered yet. Run a discovery scan to get started.",
  "dashboard.runDiscovery": "Run Discovery",
  "dashboard.resourceCount": "{count, plural, one {# resource} other {# resources}} discovered"
};

const es: TranslationCatalog = {
  "dashboard.welcome": "Bienvenido al panel de CIG",
  "dashboard.noResources": "Aún no se han descubierto recursos. Ejecuta un escaneo de descubrimiento para comenzar.",
  "dashboard.runDiscovery": "Ejecutar descubrimiento",
  "dashboard.resourceCount": "{count, plural, one {# recurso} other {# recursos}} descubiertos"
};

const zh: TranslationCatalog = {
  "dashboard.welcome": "欢迎使用 CIG 仪表盘",
  "dashboard.noResources": "尚未发现资源。运行发现扫描以开始。",
  "dashboard.runDiscovery": "运行发现",
  "dashboard.resourceCount": "已发现 {count} 个资源"
};

const catalogs: Record<SupportedLocale, TranslationCatalog> = { en, es, zh };

export default catalogs;
export { en, es, zh };
