#!/bin/sh

status=0

while read -r local_ref local_sha remote_ref remote_sha; do
  case "$local_sha" in
    0000000000000000000000000000000000000000)
      continue
      ;;
  esac

  bash scripts/validate-release-ref.sh "$local_sha" || status=$?
done

exit "$status"
